version: '3.8'

services:
  # Single repository mode service
  mcp-jujutsu-single:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-jujutsu:latest
    container_name: mcp-jujutsu-single
    environment:
      - MCP_JUJUTSU_MODE=single
      - MCP_JUJUTSU_REPO_PATH=/app/repos/single
      - MCP_JUJUTSU_HTTP_HOST=0.0.0.0
      - MCP_JUJUTSU_HTTP_PORT=8080
      - MCP_JUJUTSU_LOG_LEVEL=info
    ports:
      - "8080:8080"
    volumes:
      # Mount local repository
      - ./repos/single:/app/repos/single:rw
      # Mount SSH keys for Git operations (optional)
      - ~/.ssh:/home/mcp/.ssh:ro
      # Mount Git config (optional)
      - ~/.gitconfig:/home/mcp/.gitconfig:ro
    networks:
      - mcp-network
    restart: unless-stopped
    profiles:
      - single

  # Multi repository mode service
  mcp-jujutsu-multi:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-jujutsu:latest
    container_name: mcp-jujutsu-multi
    environment:
      - MCP_JUJUTSU_MODE=multi
      - MCP_JUJUTSU_REPOS_DIR=/app/repos/multi
      - MCP_JUJUTSU_REPO_CONFIG_PATH=/app/config/repos.json
      - MCP_JUJUTSU_HTTP_HOST=0.0.0.0
      - MCP_JUJUTSU_HTTP_PORT=8081
      - MCP_JUJUTSU_LOG_LEVEL=info
    ports:
      - "8081:8081"
    volumes:
      # Mount multiple repositories directory
      - ./repos/multi:/app/repos/multi:rw
      # Mount configuration
      - ./config:/app/config:rw
      # Mount SSH keys for Git operations (optional)
      - ~/.ssh:/home/mcp/.ssh:ro
      # Mount Git config (optional)
      - ~/.gitconfig:/home/mcp/.gitconfig:ro
    networks:
      - mcp-network
    restart: unless-stopped
    command: ["--mode=multi", "--http", "--host=0.0.0.0", "--port=8081", "--repos-dir=/app/repos/multi", "--repo-config=/app/config/repos.json"]
    profiles:
      - multi

  # Development service with source code mounted
  mcp-jujutsu-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: mcp-jujutsu:dev
    container_name: mcp-jujutsu-dev
    environment:
      - MCP_JUJUTSU_MODE=single
      - MCP_JUJUTSU_REPO_PATH=/app/repos/dev
      - MCP_JUJUTSU_HTTP_HOST=0.0.0.0
      - MCP_JUJUTSU_HTTP_PORT=8082
      - MCP_JUJUTSU_LOG_LEVEL=debug
    ports:
      - "8082:8082"
    volumes:
      # Mount source code for development
      - ./src:/app/src:rw
      - ./tests:/app/tests:rw
      - ./examples:/app/examples:rw
      - ./docs:/app/docs:rw
      # Mount repository
      - ./repos/dev:/app/repos/dev:rw
      # Mount SSH keys for Git operations (optional)
      - ~/.ssh:/home/mcp/.ssh:ro
    networks:
      - mcp-network
    working_dir: /app
    command: ["nimble", "run", "--", "--http", "--host=0.0.0.0", "--port=8082", "--verbose"]
    profiles:
      - dev

networks:
  mcp-network:
    driver: bridge

# Usage examples:
# 
# Single repository mode:
#   docker-compose --profile single up
#
# Multi repository mode:
#   docker-compose --profile multi up
#
# Development mode:
#   docker-compose --profile dev up
#
# Build images:
#   docker-compose build
#
# Run with custom config:
#   docker-compose -f docker-compose.yml -f docker-compose.override.yml up